### ISSUE TITLE
Start/stop date and time

### ISSUE THREAD

**Issue by Eframx** [iamntz/wp-caldera-forms-time-picker#1]
Hey @iamntz 

new to github so sorry if this isnt the correct way of doing things but I found an issue

I can set a starting date by typing in "today" in the field. but nothing seams to work in the end date field. I cant set the time to start at current time

The comment say "The starting date of the date picker like <code>today</code>. Please follow the same date format you used above!"
But I cant make sense of that hehe..

Is this something you can fix?

Also it would be amazing if you could set a placeholder field where I could dynamicly show current date and time

cheers!

**Comment by iamntz** [comment]
You can't have the datepicker format different by the starting/ending format.

So, you have a `date format` fied, where you can set how the date will be saved, right? Let's say you use the format `F d, Y` (which will result in dates like February 28, 2018). 

Then, if you want to set a start/end date, you need to use the same format, so if you want a max date of 31 august, you can't set `31-08-2018`, but you must use the same format as above.

I know it's not super clear, but I had no idea how to create a short explanation inline. I'm open to any suggestion :)

**Comment by Eframx** [comment]
Thanks for your reply! :D

Im sorry my brain must not be working.. how would I set a time 3 months ahead of the current date?

My date format is set to: Y-j-d H:i

**Comment by iamntz** [comment]
You can't set 3 months from _today_ (as flatpicker doesn't allow that). You can set a hard date though, so that would be `2018-09-28 00:00`.

**Comment by iamntz** [comment]
I've added the option to select a relative day, just use `-10` or `90` and you should be alright :)
