### ISSUE TITLE
Inconsistent datetime format

### ISSUE THREAD

**Issue by acharseth** [iamntz/wp-caldera-forms-time-picker#3]
Hi!

I discovered today that the generated datetime format is different for PC (tested Firefox and Chrome) and mobile devices (tested an Android (Samsung S7 with latest SW) and an iPad (with latest SW).
On the mobile devices there is a comma (',') between the date and the time while on PC there is not.
Hope you can fix this to be consistent (without comma I hope).

**Comment by iamntz** [comment]
Actually this seems to be a feature of Flatpicker: https://flatpickr.js.org/mobile-support/

**Comment by acharseth** [comment]
Hmm, native GUI is fine but inconsistent output is bad. No reason to have different output for different clients?
Maybe disableMobile would solve this but then it would also affect GUI which is not so good.

**Comment by iamntz** [comment]
Also related:

- https://github.com/flatpickr/flatpickr/issues/339
- https://github.com/flatpickr/flatpickr/issues/606
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#Value

**Comment by acharseth** [comment]
Actually the output is not affected, only the WUI. I then consider this a non issue. Sorry for the noice.
