### ISSUE TITLE
Using with Caldera and Event Calendar

### ISSUE THREAD

**Issue by hparsons56** [iamntz/wp-caldera-forms-time-picker#6]
I found this when trying to investigate how to use Caldera to add an event (using the Save As Post Type processor, and possibly the Custom Fields Post Metabox processor) using this entry for the _EventStartDate and _EventEndDate meta fields used in Event Calendar. Any chance of help with getting your plugin to work doing this?

**Comment by iamntz** [comment]
Hey @hparsons56 I've never used neither Event Calendar nor Save As Post Type processor. Can you tell me what doesn't work? What do you expect to happen vs what actually happen.

Thanks!
