### ISSUE TITLE
Can't set or remove Placeholder

### ISSUE THREAD

**Issue by MartinConde** [iamntz/wp-caldera-forms-time-picker#7]
First of all thanks a lot for this plugin! Only one tiny issue that I can't seem to figure out:

How do I edit or remove if editing is not possible, this string: dd/mm/yyyy --:--

<img width="788" alt="Screen Shot 2019-08-22 at 10 03 47" src="https://user-images.githubusercontent.com/34409953/63482736-30085f80-c4c4-11e9-87dc-78f14b0738b5.png">

I tried hiding it with css but there is nothing specific to target. If I just set the color of the whole input to transparent, the string is hidden but once a selection is made, it is hidden as well. Maybe I didn't look properly but I couldn't find where its coming from in the Plugin files either.

Any ideas?

**Comment by iamntz** [comment]
That last part is for hour/minute part, therefore you can't hide from CSS. It currently acts like the HTML standard.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
